package com.bookstore.infrastructure.persistence.util;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

public class PooledConnection implements Connection {

  /** Реальне фізичне з'єднання, що зберігається у пулі. */
  private final Connection realConnection;

  /** Посилання на пул для повернення з'єднання. */
  private final SimpleConnectionPool pool;

  /** Прапорець: чи вже повернуто це з'єднання до пулу. */
  private boolean returned = false;

  /**
   * Створює Proxy-обгортку навколо реального з'єднання.
   *
   * @param realConnection реальне JDBC з'єднання
   * @param pool пул для повернення з'єднання
   */
  public PooledConnection(Connection realConnection, SimpleConnectionPool pool) {
    this.realConnection = realConnection;
    this.pool = pool;
  }

  /**
   * Перехоплює close() і повертає з'єднання до пулу.
   *
   * <p>Реального закриття TCP-з'єднання НЕ відбувається. Метод є idempotent — повторний виклик не
   * має ефекту.
   */
  @Override
  public void close() throws SQLException {
    if (returned) {
      return;
    }
    returned = true;
    if (!realConnection.isClosed()) {
      realConnection.setAutoCommit(true);
    }
    pool.returnConnection(realConnection);
  }

  /**
   * Повертає {@code true} якщо з'єднання вже повернуто до пулу.
   *
   * <p>Для клієнта з'єднання є "закритим" після виклику {@link #close()}.
   */
  @Override
  public boolean isClosed() throws SQLException {
    return returned || realConnection.isClosed();
  }

  // --- Делегування всіх інших методів до realConnection ---

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    return realConnection.prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    return realConnection.prepareStatement(sql, autoGeneratedKeys);
  }

  @Override
  public Statement createStatement() throws SQLException {
    return realConnection.createStatement();
  }

  @Override
  public void setAutoCommit(boolean autoCommit) throws SQLException {
    realConnection.setAutoCommit(autoCommit);
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    return realConnection.getAutoCommit();
  }

  @Override
  public void commit() throws SQLException {
    realConnection.commit();
  }

  @Override
  public void rollback() throws SQLException {
    realConnection.rollback();
  }

  @Override
  public void rollback(Savepoint savepoint) throws SQLException {
    realConnection.rollback(savepoint);
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    return realConnection.setSavepoint();
  }

  @Override
  public Savepoint setSavepoint(String name) throws SQLException {
    return realConnection.setSavepoint(name);
  }

  @Override
  public DatabaseMetaData getMetaData() throws SQLException {
    return realConnection.getMetaData();
  }

  @Override
  public void setTransactionIsolation(int level) throws SQLException {
    realConnection.setTransactionIsolation(level);
  }

  @Override
  public int getTransactionIsolation() throws SQLException {
    return realConnection.getTransactionIsolation();
  }

  @Override
  public String nativeSQL(String sql) throws SQLException {
    return realConnection.nativeSQL(sql);
  }

  @Override
  public void setReadOnly(boolean ro) throws SQLException {
    realConnection.setReadOnly(ro);
  }

  @Override
  public boolean isReadOnly() throws SQLException {
    return realConnection.isReadOnly();
  }

  @Override
  public void setCatalog(String c) throws SQLException {
    realConnection.setCatalog(c);
  }

  @Override
  public String getCatalog() throws SQLException {
    return realConnection.getCatalog();
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return realConnection.getWarnings();
  }

  @Override
  public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    realConnection.releaseSavepoint(savepoint);
  }

  @Override
  public void clearWarnings() throws SQLException {
    realConnection.clearWarnings();
  }

  @Override
  public Map<String, Class<?>> getTypeMap() throws SQLException {
    return realConnection.getTypeMap();
  }

  @Override
  public void setTypeMap(Map<String, Class<?>> m) throws SQLException {
    realConnection.setTypeMap(m);
  }

  @Override
  public void setHoldability(int h) throws SQLException {
    realConnection.setHoldability(h);
  }

  @Override
  public int getHoldability() throws SQLException {
    return realConnection.getHoldability();
  }

  @Override
  public CallableStatement prepareCall(String s) throws SQLException {
    return realConnection.prepareCall(s);
  }

  @Override
  public CallableStatement prepareCall(String s, int a, int b) throws SQLException {
    return realConnection.prepareCall(s, a, b);
  }

  @Override
  public CallableStatement prepareCall(String s, int a, int b, int c) throws SQLException {
    return realConnection.prepareCall(s, a, b, c);
  }

  @Override
  public PreparedStatement prepareStatement(String s, int a, int b) throws SQLException {
    return realConnection.prepareStatement(s, a, b);
  }

  @Override
  public PreparedStatement prepareStatement(String s, int a, int b, int c) throws SQLException {
    return realConnection.prepareStatement(s, a, b, c);
  }

  @Override
  public PreparedStatement prepareStatement(String s, int[] c) throws SQLException {
    return realConnection.prepareStatement(s, c);
  }

  @Override
  public PreparedStatement prepareStatement(String s, String[] c) throws SQLException {
    return realConnection.prepareStatement(s, c);
  }

  @Override
  public Clob createClob() throws SQLException {
    return realConnection.createClob();
  }

  @Override
  public Blob createBlob() throws SQLException {
    return realConnection.createBlob();
  }

  @Override
  public NClob createNClob() throws SQLException {
    return realConnection.createNClob();
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    return realConnection.createSQLXML();
  }

  @Override
  public boolean isValid(int t) throws SQLException {
    return realConnection.isValid(t);
  }

  @Override
  public void setClientInfo(String n, String v) throws SQLClientInfoException {
    realConnection.setClientInfo(n, v);
  }

  @Override
  public void setClientInfo(Properties p) throws SQLClientInfoException {
    realConnection.setClientInfo(p);
  }

  @Override
  public String getClientInfo(String n) throws SQLException {
    return realConnection.getClientInfo(n);
  }

  @Override
  public Properties getClientInfo() throws SQLException {
    return realConnection.getClientInfo();
  }

  @Override
  public Array createArrayOf(String t, Object[] e) throws SQLException {
    return realConnection.createArrayOf(t, e);
  }

  @Override
  public Struct createStruct(String t, Object[] a) throws SQLException {
    return realConnection.createStruct(t, a);
  }

  @Override
  public void setSchema(String s) throws SQLException {
    realConnection.setSchema(s);
  }

  @Override
  public String getSchema() throws SQLException {
    return realConnection.getSchema();
  }

  @Override
  public void abort(Executor e) throws SQLException {
    realConnection.abort(e);
  }

  @Override
  public void setNetworkTimeout(Executor e, int ms) throws SQLException {
    realConnection.setNetworkTimeout(e, ms);
  }

  @Override
  public int getNetworkTimeout() throws SQLException {
    return realConnection.getNetworkTimeout();
  }

  @Override
  public Statement createStatement(int rt, int rc) throws SQLException {
    return realConnection.createStatement(rt, rc);
  }

  @Override
  public Statement createStatement(int rt, int rc, int rh) throws SQLException {
    return realConnection.createStatement(rt, rc, rh);
  }

  @Override
  public <T> T unwrap(Class<T> i) throws SQLException {
    return realConnection.unwrap(i);
  }

  @Override
  public boolean isWrapperFor(Class<?> i) throws SQLException {
    return realConnection.isWrapperFor(i);
  }
}
